#-------------------------------
# Site Settings
title: Retreats in Österreich
logo: # You can add own logo. For example "/images/logo.png".
description: Finde dein nächstes Retreat ganz in deiner Nähe. Unsere Vision ist es Retreats in Österreich leichter auffindbar zu machen und die Retreat-Organisatoren bei der Orga-Arbeit zu unterstützen.


#-------------------------------
# Author Global Settings
author:
  author__name: Hallo, ich bin Lukas.
  author__bio: Mein Ziel ist es, die Retreat-Szene in Österreich besser zu vernetzen und die tollen regionalen Retreats, die wir haben, leichter auffindbar zu machen.
  author__avatar: /images/01-lukas.jpg


#-------------------------------
# Navigation Settings
menu__settings:
  menu__items:
    - title: 'Retreat-Suchende'
      url: '/retreats/'
    - title: 'Retreat-Anbieter'
      url: '/retreat-anbieter/'
    - title: 'Über uns'
      submenu:
      - url: '/philosophie/'
        title: 'Was, wie, warum?'
      - url: '/ueber-uns/'
        title: 'Wer steckt dahinter'
      - url: '/team/'
        title: 'Unser Netzwerk'
    - title: 'Kontakt'
      url: '/kontakt/'


#-------------------------------
# Hero Settings
hero:
  hero__title: Unsere Vision ist es Retreats in Österreich leichter auffindbar zu machen und die Organisatoren von Retreats zu unterstützen.


#-------------------------------
# Blog Settings
blog:
  blog__title: Die nächsten Retreats in Österreich
  blog__description: Hier unsere Empfehlungen für dich. Solltest du dir nicht sicher sein was genau zu dir passt, <a hreF="/kontakt/">melde dich liebend gerne</a> bei uns, wir helfen dir gerne weiter.


#-------------------------------
# Recommended Tag Settings
tag:
  enable: true
  tag__title: Veranstaltungsorte unserer Kooperationspartner
  tag__name: Motivation


#-------------------------------
# Newsletter Settings
mailchimp:
  enable: true
  mailchimp__identifier: frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3 # Add your MailChimp form identifier. For example - frnla.us6.list-manage.com/subscribe/post?u=6314d69a3f315af7ce3fb00a0&amp;id=3038727cc3
  mailchimp__title: Interesse geweckt?
  mailchimp__description: Dann trage dich in unseren E-Mail Verteiler ein. Du wirst ein paar Mal im Jahr von uns hören.
  mailchimp__input__text: Deine E-Mail
  mailchimp__button__text: Abonnieren
  # mailchimp__background__image: "/images/stockphotos/generic/yogi-sunrise-in-the-mountains eneko-urunuela-I2YSmEUAgDY-unsplash.jpg"
  mailchimp__background__image: "/images/stockphotos/generic/yogi-pose stephanie-greene-1aB-1s4BIEo-unsplash.jpg"


#-------------------------------
# Footer Settings

# Footer Navigation
footer__menu__settings:
  menu__items:
    - title: 'Start'
      url: '/'
    - title: 'Über uns'
      url: '/ueber-uns/'
    - title: 'Impressum'
      url: '/impressum/'
    - title: 'Kontakt'
      url: '/kontakt/'
    

# Social Links
# social:
# - {icon: "ion-logo-instagram", color: "#e4405f", name: Instagram, link: "https://instagram.com"}


#-------------------------------
# Contact Settings
contact:
  email: retreats.near.you@gmail.com

# NOTE
# Dann theme comes with a contact form built-in. You can use this form with Formspree (https://formspree.io/) service and get up to 50 submissions for free. Also, you can easily switch to another service if you want.


#-------------------------------
# Comment Section (Disqus)
disqus:
  enable: false
  disqus__identifier: anvod-studio-test # Add your shortname for Disqus Comment. For example anvod-studio-test


#-------------------------------
# Google Analytics
google-analytics: # Add your GA Tracking Id
